### ISSUE TITLE
Bug Report: wrong elixir version installed in cimg/elixir v1.16.x and v1.17.x

### ISSUE THREAD

**Issue by lwld** [CircleCI-Public/cimg-elixir#156]
**Describe the bug**

All cimg/elixir images tagged with patch versions of `1.16` and `1.17` contain the wrong elixir version (patch `.0` instead of what is tagged):
- images tagged with `1.16.1`, `1.16.2`, `1.16.3` contain elixir version `1.16.0`
- images tagged with `1.17.1`, `1.17.2` contain elixir version `1.17.0`

It seems that the elixir version was never updated when these images were published.

Images tagged with `1.15.8` are still correct, they contain elixir version `1.15.8`.

Tested with `-erlang-26.2.1` images.

**To Reproduce**

Minimal sample project that reproduces the issue: https://github.com/Kittysplit/cimg_test
The build results on commits show which tag versions are correct and which aren't: https://github.com/Kittysplit/cimg_test/commits/main/

Sample config: 
```
version: 2.1

workflows:
  check:
    jobs:
      - compile

jobs:
  compile:
    docker:
      - image: cimg/elixir:1.17.2-erlang-26.2.1
    steps:
      - checkout
      - run:
          name: "Check elixir version"
          command: elixir --version
      - run:
          name: "Install hex"
          command: mix local.hex --force
      - run:
          name: "Install rebar"
          command: mix local.rebar --force
      - run:
          name: "Get elixir dependencies"
          command: mix deps.get
      - run:
          name: "Build elixir"
          command: mix compile --warnings-as-errors
      - run:
          name: "Run elixir tests"
          command: mix test
```

The `elixir --version` step output already shows that it's running the wrong elixir version:
```
Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:36:8] [ds:36:8:10] [async-threads:1] [jit:ns]

Elixir 1.17.0 (compiled with Erlang/OTP 26)
```

If it contains an elixir project and the elixir version is fixed including patch version (with `elixir: "~> 1.17.2"`), `mix compile` / `mix test` will fail with `** (Mix) You're trying to run :cimg_test on Elixir v1.17.0 but it has declared in its mix.exs file it supports only Elixir ~> 1.17.2`. See sample project linked above to reproduce.

**Expected behavior**

Images should contain the tagged elixir version, or higher patch version for images tagged with only a minor release (as described in https://github.com/CircleCI-Public/cimg-elixir?tab=readme-ov-file#tagging-scheme)

**Workarounds**

- Only use images tagged with minor version (eg. `1.17`, not `1.17.1`/`1.17.2`)
- Set elixir version without patch version in `elixir: "~> 1.17"`, **however** this still doesn't use the tagged patch version.

**Screenshots and Build Links**

- tag: `1.15.8`: ✅ https://app.circleci.com/pipelines/github/Kittysplit/cimg_test/1/workflows/a853f706-91a7-457c-835d-dd5972e42d9f
- tag: `1.16`: ✅ https://app.circleci.com/pipelines/github/Kittysplit/cimg_test/2/workflows/2eb1c7a9-6f98-45f2-b8d9-5b723d4c60da
- tag: `1.16.0`: ✅ https://app.circleci.com/pipelines/github/Kittysplit/cimg_test/3/workflows/2696e527-4844-4e5a-a944-16c36119647b
- tag: `1.16.1`: ❌ https://app.circleci.com/pipelines/github/Kittysplit/cimg_test/4/workflows/2e47a4c8-7e52-443f-86b0-938c9e2c6d64
- tag: `1.16.2`: ❌ https://app.circleci.com/pipelines/github/Kittysplit/cimg_test/5/workflows/2488b32d-0f8f-46b2-8ead-023b7f2ceb03
- tag: `1.16.3`: ❌ https://app.circleci.com/pipelines/github/Kittysplit/cimg_test/6/workflows/f52426ca-1589-4709-a99d-5dbb156c62ee
- tag: `1.17`: ✅ https://app.circleci.com/pipelines/github/Kittysplit/cimg_test/7/workflows/e67e96dc-586b-4427-bd74-525933848ffc
- tag: `1.17.0`: ✅ https://app.circleci.com/pipelines/github/Kittysplit/cimg_test/8/workflows/806e3c7d-3b3c-4314-a059-5dc88c7b3f3d
- tag: `1.17.1`: ❌ https://app.circleci.com/pipelines/github/Kittysplit/cimg_test/9/workflows/5c599e5a-45c9-44c8-b438-816a2cb98a17
- tag: `1.17.2`: ❌ https://app.circleci.com/pipelines/github/Kittysplit/cimg_test/10/workflows/d1c0c41e-d3f8-4e8b-9b90-063150a01f79

Screenshots:

See elixir version in image container tag during spin up vs `elixir --version` output:

<img width="954" alt="Screenshot 2024-07-12 at 17 29 32" src="https://github.com/user-attachments/assets/ab5a9cce-7573-432e-ad9c-9aab0814e704">

Error on `mix compile`:

<img width="1047" alt="Screenshot 2024-07-12 at 17 29 44" src="https://github.com/user-attachments/assets/169ee2c7-927e-4e15-a668-0d8ca7d91284">

**Additional context**
none
